### ISSUE TITLE
ux changes

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Cell-Phone-Repair#1]
1. add logo somewhere above the fold. 
2.  change copy to meet our restrictions
3. add actual review copy
4. remove footer.
5. provide favicon asset (24x24)

https://loving-benz-7093f0.netlify.com/

**Comment by bamboochow** [comment]
1. added in banner
2. copy edited, @paulchrisluke pls double check
3. review copy added, @atharva3010 pls make sure spacing is accurate
![image](https://user-images.githubusercontent.com/14948326/59920305-5114eb80-9454-11e9-95bc-d238b4a42f62.png)
4. footer removed
5. favicon asset located in ui library

**Comment by atharva3010** [comment]
okay
